// Original StudyFlow lesson notes. Videos remain hosted by their credited creators.
const lesson = (title, explanation, example, exercise, minutes = 25) => ({
  title,
  description: explanation.split(". ")[0] + ".",
  content: `CONCEPTS\n${explanation}\n\nWORKED EXAMPLE\n${example}\n\nPRACTICE LAB\n${exercise}\n\nCHECK YOUR UNDERSTANDING\nExplain the decisions in your solution, test an edge case, and describe one alternative approach. Keep your work in a portfolio repository.`,
  minutes,
});
const section = (title, ...lessons) => ({ title, lessons });
const course = (
  key,
  title,
  category,
  level,
  subtitle,
  description,
  outcomes,
  requirements,
  video,
  modules,
) => ({
  key,
  title,
  category,
  level,
  subtitle,
  description,
  outcomes: outcomes.join("\n"),
  requirements: requirements.join("\n"),
  video_url: `https://www.youtube.com/watch?v=${video}`,
  resource_credit:
    "Companion video: freeCodeCamp.org on YouTube. StudyFlow lesson notes and exercises are independent; use the video chapter list to find each topic.",
  modules,
});
module.exports = [
  course(
    "web",
    "Web Development Fundamentals",
    "Web Development",
    "Beginner",
    "Build accessible, responsive websites from your very first HTML tag.",
    "Create a complete personal portfolio while learning semantic HTML, accessible forms and modern CSS. Each module combines explanations, worked examples and a practical lab. Finish with a responsive project that works on mobile and with a keyboard.",
    [
      "Structure pages using semantic HTML",
      "Build accessible forms with clear validation",
      "Create responsive layouts with Flexbox and Grid",
      "Deliver a tested personal portfolio",
    ],
    ["A browser and a code editor", "No previous coding experience"],
    "dX8396ZmSPk",
    [
      section(
        "HTML",
        lesson(
          "Introduction to HTML",
          "HTML describes the meaning and structure of a document. Browsers parse nested elements into a document tree. A document needs a doctype, a language, a title and a viewport declaration; these make the page predictable and useful to assistive technology.",
          '<!doctype html>\n<html lang="en">\n<head><meta charset="utf-8"><title>My portfolio</title></head>\n<body><main><h1>Hello, I am Sam</h1><p>Student developer.</p></main></body>\n</html>',
          "Create an index.html file, open it locally, and inspect the document tree in browser developer tools. Add a meaningful title and compare the page source with the rendered page.",
        ),
        lesson(
          "HTML Elements",
          "Use headings to express a hierarchy, paragraphs for prose and lists for related items. Semantic landmarks such as header, nav, main and footer help people navigate. Links navigate to a resource; buttons trigger an action. Alternative text should describe the purpose of an image rather than its file name.",
          '<nav aria-label="Main"><a href="#projects">Projects</a></nav>\n<section id="projects"><h2>Recent projects</h2><ul><li>Study tracker</li></ul></section>',
          "Build the navigation and projects section of your portfolio. Navigate using only Tab and Enter. Verify that heading levels remain in order and that link names make sense without surrounding text.",
        ),
        lesson(
          "Forms",
          "Every input needs an accessible label and an appropriate type. Native required, minlength and email checks improve feedback, but the server must validate the same values. Group related controls with fieldset and legend. Show errors close to the affected input and preserve what the learner typed.",
          '<label for="email">Email</label>\n<input id="email" name="email" type="email" required>\n<button type="submit">Send enquiry</button>',
          "Create a contact form with name, email and message fields. Test empty submission, an invalid email and a long message. Explain why browser validation cannot secure an API.",
        ),
      ),
      section(
        "CSS",
        lesson(
          "CSS Basics",
          "CSS rules match elements through selectors. The cascade resolves competing declarations using origin, importance, specificity and order. The box model consists of content, padding, border and margin. Applying border-box makes widths include padding and borders, simplifying predictable layout.",
          "* { box-sizing: border-box; }\n.project { padding: 1rem; border: 1px solid #ddd; border-radius: .75rem; }\n.project h2 { margin-bottom: .5rem; }",
          "Style your project cards and inspect computed styles. Introduce two conflicting color rules and explain which one wins. Check readable contrast for text, buttons and focus states.",
        ),
        lesson(
          "Flexbox",
          "Flexbox arranges content along one main axis and one cross axis. Use gap for space between items and flex-wrap when content should move onto another line. Justify-content distributes items along the main axis; align-items works on the cross axis. Avoid fixed heights for text-heavy cards.",
          ".navigation { display: flex; flex-wrap: wrap; gap: 1rem; align-items: center; }\n.navigation .brand { margin-right: auto; }",
          "Make your navigation wrap at narrow widths. Build a card with its action aligned at the bottom. Test a long course title and a user who increases text size to 200%.",
        ),
        lesson(
          "Grid",
          "CSS Grid controls rows and columns together. A responsive card layout can use auto-fit with minmax to choose the number of columns from available space. Keep the source order meaningful so keyboard navigation matches the visual reading order. Use media queries only when content needs a different arrangement.",
          ".projects { display: grid; grid-template-columns: repeat(auto-fit, minmax(240px, 1fr)); gap: 1rem; }",
          "Finish your portfolio with a responsive project grid. Test at 390px and 1280px, with three and seven cards. Document any overflow problems and the CSS changes that resolved them.",
        ),
      ),
    ],
  ),
  course(
    "database",
    "Database Management",
    "Database",
    "Intermediate",
    "Design relational schemas and answer real questions with SQL.",
    "Model a university course catalogue, translate it into a relational schema and query enrolment data. Practice constraints, joins, aggregation and transactions using PostgreSQL. Your final deliverable is an ER diagram, migration script and a set of reporting queries.",
    [
      "Design an ER diagram and normalised tables",
      "Use keys and constraints to preserve integrity",
      "Write joins and aggregate reporting queries",
      "Apply transactions to related updates",
    ],
    [
      "Basic programming knowledge",
      "PostgreSQL or the project Docker database",
    ],
    "HXV3zeQKqGY",
    [
      section(
        "Relational Design",
        lesson(
          "Entities and Relationships",
          "An entity is a kind of thing with attributes, such as a learner or course. Relationships describe how entities connect. A many-to-many relationship needs an associative table: an enrolment links one learner to one course. Separate data that changes independently and avoid storing a list of IDs inside one field.",
          "Users(id, name, email)\nCourses(id, title, educator_id)\nEnrolments(id, user_id, course_id)\nA course has many enrolments; a user can have many enrolments.",
          "Draw an ER diagram for a university LMS. Include modules, lessons and lesson progress. State the cardinality of every relationship and justify which attributes belong in each entity.",
        ),
        lesson(
          "Keys and Constraints",
          "A primary key identifies a row. A foreign key references another table and prevents broken relationships. A unique constraint prevents duplicate business facts. A check constraint restricts valid values. Decide deletion behavior deliberately: course content may cascade, while an educator with owned courses should not disappear silently.",
          "CREATE TABLE enrolments (\n id SERIAL PRIMARY KEY,\n user_id INTEGER REFERENCES users(id),\n course_id INTEGER REFERENCES courses(id),\n UNIQUE(user_id, course_id)\n);",
          "Create your schema and try inserting a duplicate enrolment and a missing course ID. Record the errors. Explain why checking duplicates only in frontend code is insufficient.",
        ),
      ),
      section(
        "SQL",
        lesson(
          "Select Queries",
          "SELECT chooses columns, WHERE filters rows and ORDER BY makes result order explicit. Bind values as parameters instead of building SQL by concatenating input. NULL represents missing information and requires IS NULL rather than equality comparisons. LIMIT is useful for recent activity lists.",
          'SELECT title, category FROM courses\nWHERE status = $1 AND title ILIKE $2\nORDER BY created_at DESC LIMIT 10;\nParameters: ["PUBLISHED", "%python%"]',
          "Write queries for published beginner courses, users created this month and courses without a thumbnail. Test searches containing apostrophes and explain how parameter binding handles them.",
        ),
        lesson(
          "Joins",
          "An inner join returns matching rows from both sides. A left join preserves rows from the left side even when a related record is absent. Join on keys, not display names. Count carefully: joining a course to lessons and enrolments at once can multiply rows and inflate statistics.",
          "SELECT c.title, COUNT(e.id) AS learners\nFROM courses c LEFT JOIN enrolments e ON e.course_id = c.id\nGROUP BY c.id, c.title;",
          "List every course with its educator and enrolment count, including empty courses. Compare COUNT(*) with COUNT(e.id) and explain why they differ after a left join.",
        ),
      ),
      section(
        "Integrity & reporting",
        lesson(
          "Aggregation and Progress Reports",
          "Aggregate functions summarise rows. GROUP BY defines each group and HAVING filters groups after aggregation. Progress uses completed lessons divided by the current course lesson count, not a manually maintained percentage. Handle zero lessons explicitly and ensure each completion is counted once.",
          "progress = total_lessons === 0 ? 0 : Math.round(completed_lessons * 100 / total_lessons);\nExample: 8 completed out of 12 gives 67%.",
          "Write a course progress report for every learner. Test a learner with zero completions, a fully completed course and a course with no lessons. Explain the effect of deleting a lesson.",
        ),
        lesson(
          "Transactions and Indexes",
          "A transaction groups updates so they either all commit or all roll back. This is essential when leaving a course removes both enrolment and progress. Indexes accelerate selected lookups but cost storage and write time. Use EXPLAIN to observe a query plan rather than assuming every column needs an index.",
          "BEGIN;\nDELETE FROM lesson_progress WHERE user_id = 12 AND lesson_id IN (...);\nDELETE FROM enrolments WHERE id = 25;\nCOMMIT;",
          "Implement a two-step update inside a transaction and force the second step to fail. Verify the first update is rolled back. Add an index on a frequently filtered foreign key and inspect its query plan.",
        ),
      ),
    ],
  ),
  course(
    "python",
    "Python Programming",
    "Programming",
    "Beginner",
    "Write useful Python programs, from variables to a command-line project.",
    "Learn Python through small programs you can run and explain. Work with collections, functions, files and error handling, then build a command-line study planner. Labs emphasise readable code, input validation and testing edge cases.",
    [
      "Use Python values, collections and control flow",
      "Write reusable functions with clear inputs",
      "Read and write structured files safely",
      "Build and test a command-line study planner",
    ],
    ["Python 3 installed", "A code editor; no coding experience required"],
    "rfscVS0vtbw",
    [
      section(
        "Python Basics",
        lesson(
          "Variables and Types",
          "Variables bind names to values. Python supports integers, floats, booleans and strings, and operations depend on type. Input returns text, so convert it deliberately. Avoid shadowing built-in names such as list or str. F-strings make formatted output readable.",
          'hours = 3\nrate = 12.5\ntotal = hours * rate\nprint(f"Estimated cost: {total:.2f}")',
          "Build a study-time calculator that asks for minutes per day and number of days. Convert the inputs and display the total hours. Try empty, negative and non-numeric input.",
        ),
        lesson(
          "Loops",
          "A for loop iterates over a collection; a while loop repeats until a condition changes. Keep the stopping condition clear and avoid modifying a list as you iterate through it. Use enumerate when you need both an index and a value. Break and continue should make control flow easier to understand.",
          'tasks = ["Read", "Practice", "Review"]\nfor number, task in enumerate(tasks, start=1):\n    print(f"{number}. {task}")',
          "Print a numbered study checklist. Extend it to ask whether each task is complete and calculate the completion percentage. Test an empty checklist without dividing by zero.",
        ),
        lesson(
          "Functions",
          "Functions give a name to a reusable operation. Parameters describe inputs; return values describe outputs. Keep computation separate from printing or asking for input so it can be tested. Default arguments should be immutable values; mutable defaults can accidentally share state between calls.",
          "def progress(completed, total):\n    if total == 0:\n        return 0\n    return round(completed * 100 / total)\n\nassert progress(2, 4) == 50",
          "Extract your checklist progress calculation into a function. Test zero tasks, all tasks complete and an invalid count. Write a short docstring describing valid inputs.",
        ),
      ),
      section(
        "Collections & files",
        lesson(
          "Lists and Dictionaries",
          "Lists preserve an ordered sequence of values. Dictionaries associate unique keys with values and are useful for records and lookups. Choose a structure based on the operations you need: indexing, membership or lookup by identity. Copy a collection deliberately when you do not want shared mutations.",
          'task = {"title": "Review SQL", "completed": False}\ntasks = [task]\ncompleted = [t for t in tasks if t["completed"]]',
          "Represent study tasks as dictionaries inside a list. Add filtering by completion and searching by title. Explain how changing a referenced dictionary affects the containing list.",
        ),
        lesson(
          "Reading and Writing JSON",
          "JSON is a text format for simple structured data. Use a context manager to close files reliably and specify UTF-8 for portable text. Serialise a consistent shape and validate the loaded values. Handle missing files as an expected first-run situation rather than hiding every exception.",
          'import json\nwith open("tasks.json", "w", encoding="utf-8") as file:\n    json.dump(tasks, file, indent=2)',
          "Save your task list and load it after restarting the program. Test a missing file and invalid JSON. Preserve the previous file until you know the new data is valid.",
        ),
      ),
      section(
        "Reliable programs",
        lesson(
          "Exceptions and Validation",
          "Exceptions communicate operations that could not complete. Catch the specific exception you can handle, give useful feedback and avoid a bare except that hides programming mistakes. Validate inputs at the boundary of your program. Separate expected user errors from defects in the code.",
          'try:\n    minutes = int(input("Minutes: "))\n    if minutes < 0:\n        raise ValueError("Use a non-negative value")\nexcept ValueError as error:\n    print(f"Invalid input: {error}")',
          "Add validation to every command in your planner. Ensure an unknown command, negative duration and unreadable file each produce a clear message without corrupting saved tasks.",
        ),
        lesson(
          "Study Planner Capstone",
          "A complete program combines data, operations and a user interface. Implement one command at a time and keep functions small enough to test. A useful README explains installation, commands and examples. Your project should recover from common errors and preserve tasks between runs.",
          "Commands: add, list, complete, summary, quit.\nData: title, estimated_minutes, completed.\nSummary: tasks completed and remaining estimated minutes.",
          "Deliver your working planner with at least six test cases. Ask another person to follow the README. Document one usability issue they found and the change you made.",
          40,
        ),
      ),
    ],
  ),
  course(
    "javascript",
    "JavaScript: From Fundamentals to Interactive Apps",
    "Web Development",
    "Beginner",
    "Turn static pages into interactive, data-driven experiences.",
    "Explore the language behind browser applications through a task-manager project. Understand values, array transformations, DOM events and asynchronous requests. Finish with a resilient interface that handles loading, success and failure states.",
    [
      "Transform data with arrays and objects",
      "Handle browser events without inline scripts",
      "Fetch API data and show loading/error states",
      "Build a tested interactive task manager",
    ],
    ["Basic HTML and CSS", "A modern browser and code editor"],
    "jS4aFq5-91M",
    [
      section(
        "Language essentials",
        lesson(
          "Values, Scope and Equality",
          "Use const for bindings you do not reassign and let when reassignment is necessary. Objects remain mutable even when their binding uses const. Block scope keeps temporary variables local. Prefer strict equality so strings and numbers are not silently coerced into the same value.",
          'const course = { title: "JavaScript", lessons: 6 };\ncourse.lessons += 1;\nconsole.log("6" === 6); // false',
          "Write a lesson progress calculator. Validate that the counts are numbers before calculating. Explain the difference between reassigning a const binding and editing one of its object properties.",
        ),
        lesson(
          "Array Methods and Objects",
          "Map transforms each item, filter selects items and reduce accumulates a result. Return new arrays when transforming UI state instead of mutating an existing value. Use meaningful variable names and choose a loop when it communicates the task more clearly than a chain of methods.",
          'const tasks = [{title:"Read",done:true},{title:"Code",done:false}];\nconst remaining = tasks.filter(task => !task.done);\nconst names = remaining.map(task => task.title);',
          "Create a list of courses and derive category counts, incomplete courses and a list of titles. Verify that the original array remains unchanged after each operation.",
        ),
      ),
      section(
        "The interactive browser",
        lesson(
          "DOM Selection and Events",
          "The DOM is the browser representation of a page. Select elements, register listeners and update text or attributes in response to events. Use textContent for user-provided text instead of injecting HTML. Event delegation can handle many similar child controls with one listener.",
          'document.querySelector("#add-task").addEventListener("click", () => {\n  const item = document.createElement("li");\n  item.textContent = "New study task";\n  document.querySelector("#tasks").append(item);\n});',
          "Build an add-task form. Prevent empty tasks, clear the input after success and support keyboard submission. Enter text containing HTML tags and verify it displays as text.",
        ),
        lesson(
          "Forms and Local State",
          "Keep application data separate from the DOM and render the interface from that data. Form submission should prevent the default page navigation when the application handles the action. Browser storage is useful for non-sensitive preferences but is not a substitute for server authentication.",
          "const state = { tasks: [] };\nfunction addTask(title) {\n  state.tasks = [...state.tasks, { title, done: false }];\n  renderTasks(state.tasks);\n}",
          "Store and render tasks from a state object. Add completion and deletion controls. Explain which information is safe to keep in localStorage and which should remain server-side.",
        ),
      ),
      section(
        "Working with APIs",
        lesson(
          "Promises and Async/Await",
          "A promise represents work that finishes later. Await pauses the surrounding async function, not the entire browser. Fetch does not throw for HTTP error responses, so check response.ok. A finally block can reliably remove a loading state whether the request succeeded or failed.",
          'async function loadCourses() {\n  const response = await fetch("/api/courses");\n  if (!response.ok) throw new Error("Unable to load courses");\n  return response.json();\n}',
          "Load the portal catalogue into a small standalone page. Show separate loading, empty and error states. Simulate an unavailable API and verify the interface lets the user retry.",
        ),
        lesson(
          "Interactive App Capstone",
          "A finished interface should remain understandable when data is empty or a request fails. Disable repeated submissions while a mutation is pending and preserve user input on error. Test with a slow connection and keyboard navigation. Document your state transitions rather than relying on incidental DOM behavior.",
          "States: idle → submitting → success or error.\nOn error: show message, preserve draft, enable retry.\nOn success: update data, clear draft, move focus sensibly.",
          "Deliver your task manager with filtering, completion counts and persistent non-sensitive data. Record tests for empty data, rapid clicks, long titles and request failures.",
          40,
        ),
      ),
    ],
  ),
  course(
    "react",
    "React Application Development",
    "Web Development",
    "Intermediate",
    "Build reusable components and connect a React interface to real APIs.",
    "Build a course explorer with reusable cards, searchable data and a detail page. Learn state, effects, forms and routing while paying attention to accessibility and network failures. Companion material covers foundational React; the portal examples use function components and hooks.",
    [
      "Compose reusable React components",
      "Manage forms and derived state",
      "Fetch data safely with effects",
      "Build accessible routes and protected views",
    ],
    ["Comfort with JavaScript arrays and functions", "Basic HTML/CSS and npm"],
    "bMknfKXIFA8",
    [
      section(
        "Components & state",
        lesson(
          "JSX, Props and Composition",
          "JSX describes a component tree using JavaScript expressions and familiar element syntax. Props are read-only inputs from a parent. Composition lets a small component work in several contexts. Use stable keys from data identity when rendering lists so React can preserve the right local state.",
          "function CourseCard({course}) {\n  return <article><h2>{course.title}</h2><p>{course.category}</p></article>;\n}\n// courses.map(course => <CourseCard key={course.id} course={course} />)",
          "Create a course card and reuse it in a catalogue and dashboard. Test missing optional content and long titles. Explain why an array index can be a poor key when items are reordered.",
        ),
        lesson(
          "State and Derived Values",
          "State stores information that changes through interaction. Derive filtered results and counts from source data instead of duplicating them in separate state variables. Treat arrays and objects as immutable when updating state. Functional updates are useful when the next value depends on the previous one.",
          'const [query,setQuery] = useState("");\nconst visible = courses.filter(c => c.title.toLowerCase().includes(query.toLowerCase()));',
          "Add search and category controls to your catalogue. Derive the visible course count from the result array. Update one course title without mutating the existing array.",
        ),
      ),
      section(
        "Data & navigation",
        lesson(
          "Effects and API Loading",
          "Effects synchronise a component with systems outside React, such as an API. Include changing inputs in dependencies and prevent outdated requests from overwriting current results. Model loading, error, empty and ready states explicitly. Avoid an effect for calculations that can happen during rendering.",
          "useEffect(() => {\n  let current = true;\n  loadCourse(id).then(data => { if (current) setCourse(data); });\n  return () => { current = false; };\n}, [id]);",
          "Create a course detail loader. Switch between course IDs quickly and simulate failures. Confirm that content from the previous route does not appear as the new course.",
        ),
        lesson(
          "Routing and Protected Views",
          "Routes map URLs to views and route parameters identify resources. Protecting a frontend route improves navigation but does not secure the API. Session identity must come from the server, and server permissions must still reject forbidden mutations. Preserve meaningful URLs so detail pages work after a refresh.",
          "/courses/:id → course details\n/educator/courses/:id/edit → educator editor\n/api/auth/me → server session identity",
          "Build a list and detail route. Add a frontend role guard and call a protected API directly with the wrong role. Explain the separate purposes of these two checks.",
        ),
      ),
      section(
        "Forms & delivery",
        lesson(
          "Controlled Forms and Feedback",
          "Controlled inputs use React state as their current value. Each field needs a label, appropriate input type and useful error feedback. Disable the submit button while saving and preserve the draft if saving fails. Do not let a background refresh erase a user edit without notice.",
          'const [title,setTitle] = useState("");\n<label>Course title<input value={title} onChange={e => setTitle(e.target.value)} required /></label>',
          "Build a course form with title, category and description. Show server validation errors beside the form. Test a double-click and a request that returns 403.",
        ),
        lesson(
          "Course Explorer Capstone",
          "Combine components, routing and API state into a coherent experience. Share small, useful components rather than creating an abstraction for every line of code. Test the journey a user follows, including refresh and failure states. Run a production build before considering the application ready.",
          "Acceptance criteria: search, category filter, course details, enrolment feedback and responsive cards.\nQuality checks: lint, build, browser journey and no console errors.",
          "Deliver your course explorer with a setup guide and a short architecture diagram. Ask a peer to use it on mobile and make one improvement from their feedback.",
          40,
        ),
      ),
    ],
  ),
  course(
    "node",
    "Backend APIs with Node.js & Express",
    "Web Development",
    "Intermediate",
    "Design secure HTTP APIs and connect them to a relational database.",
    "Develop an API for a study tracker using Express and PostgreSQL. Cover routes, middleware, validation, sessions, ownership and database transactions. Finish with an integration test suite that verifies both successful and forbidden requests.",
    [
      "Design clear resource-based API routes",
      "Validate inputs and centralise error responses",
      "Enforce session, role and ownership rules",
      "Test a database-backed API end to end",
    ],
    ["JavaScript and async/await", "Node.js and a local PostgreSQL database"],
    "Oe421EPjeBE",
    [
      section(
        "HTTP & Express",
        lesson(
          "Resources, Methods and Status Codes",
          "An API should name resources consistently and use methods to describe actions. GET reads, POST creates, PUT updates and DELETE removes. Use status codes that communicate the result: 201 for creation, 400 for validation, 401 for no session, 403 for forbidden access and 404 for missing resources.",
          "GET /api/courses\nPOST /api/courses\nPUT /api/courses/42\nDELETE /api/courses/42",
          "Design endpoints for courses, modules, lessons and enrolments. Write one example request and response for each. Explain how 401 differs from 403.",
        ),
        lesson(
          "Middleware and Error Handling",
          "Middleware executes in registration order and can attach information to a request or end it early. JSON parsing, rate limiting and session lookup should run before routes that need them. Place error handling after routes and return useful messages without exposing internal stack traces.",
          'app.use(express.json());\napp.use(sessionMiddleware);\napp.use("/api/courses", courseRouter);\napp.use((error,req,res,next) => res.status(500).json({message:"Request failed"}));',
          "Add a missing-resource response and one error handler to your API. Test malformed JSON, a missing ID and a database failure. Verify that every response has a consistent shape.",
        ),
      ),
      section(
        "Data & access control",
        lesson(
          "PostgreSQL Queries and Validation",
          "Use placeholders for SQL values, and validate data before it reaches the database. Database constraints remain the last line of defence for duplicate or inconsistent records. A connection pool reuses connections; release an explicitly acquired client in finally. Keep query results separate from transport details.",
          'const result = await db.query(\n  "SELECT id,title FROM courses WHERE id=$1", [courseId]\n);\nif (!result.rowCount) throw new Error("Course not found");',
          "Implement course creation with required title/category fields. Test SQL-looking input as ordinary data. Map a unique constraint error to a friendly conflict response.",
        ),
        lesson(
          "Sessions, Roles and Ownership",
          "A session associates an opaque cookie with a server-side account. Look up the current role from the database instead of trusting a user ID in a request body. Role checks decide who may manage courses; ownership checks decide which courses they may manage. Hash passwords with a password hashing algorithm.",
          'if (!req.user) return res.status(401).json({message:"Log in"});\nif (course.educator_id !== req.user.id && req.user.role !== "ADMIN")\n  return res.status(403).json({message:"Own courses only"});',
          "Create two educators and attempt to edit the second account’s course using the first account. Test learner and unauthenticated requests as well. Verify that all are rejected by the API.",
        ),
      ),
      section(
        "Testing & delivery",
        lesson(
          "Transactions and Integration Tests",
          "Integration tests should cross the HTTP and database boundary. Use unique fixture records and clean them up so tests can repeat. Verify negative cases, not just successful CRUD. Transactions help keep related changes consistent when one step fails.",
          "Journey: register → create draft → add lesson → publish → enrol → complete → logout/login → verify progress.\nNegative cases: duplicate enrolment, wrong owner, inactive account.",
          "Write an HTTP test for the learner journey and one for educator ownership. Assert response status and stored database values. Run the suite twice and confirm it leaves no fixture accounts behind.",
        ),
        lesson(
          "Study Tracker API Capstone",
          "A usable API includes a repeatable schema, development seed, environment example and setup instructions. Keep secrets out of tracked files. Test the service from a clean setup and make failures such as an unavailable database understandable. Explain the frontend-to-API-to-database flow.",
          "Deliverables: routes, schema, seed, environment example, integration tests and README.\nHealth endpoint: performs a lightweight database query.",
          "Package your API for a peer to run. Document all required environment variables and expected role permissions. Show your tests rejecting one unauthorized request.",
          40,
        ),
      ),
    ],
  ),
  course(
    "git",
    "Git & GitHub for Collaborative Projects",
    "Developer Tools",
    "Beginner",
    "Make confident commits, work on branches and review changes as a team.",
    "Learn a practical Git workflow for university group projects. Track meaningful changes, branch safely, resolve conflicts and prepare reviewable pull requests. Finish with a collaboration exercise and a repository another developer can understand.",
    [
      "Explain working tree, index and commit history",
      "Use branches for focused features",
      "Resolve conflicts without losing work",
      "Write useful commits and pull requests",
    ],
    ["A code editor and Git installed", "A small project folder"],
    "zTjRZNkhiEU",
    [
      section(
        "Local version control",
        lesson(
          "Working Tree, Staging and Commits",
          "Git tracks snapshots of a repository. The working tree contains current files, the index selects changes for the next commit and history stores completed commits. Inspect a diff before staging so unrelated edits do not enter a checkpoint. A useful commit states the behavior or problem addressed.",
          'git status\ngit diff\ngit add src/course.js\ngit commit -m "Add course search by category"',
          "Create a repository for a small app. Make two independent edits and commit them separately. Explain why each commit can be understood and reviewed on its own.",
        ),
        lesson(
          "History, Ignore Rules and Secrets",
          "Log shows the history, diff compares states and show inspects a commit. Ignore generated output, installed dependencies and local secrets. An ignore rule does not remove a file already tracked. If a real secret enters history, rotate it rather than assuming deletion makes it safe.",
          "git log --oneline\ngit show HEAD\n# .gitignore\nnode_modules/\ndist/\n.env",
          "Add an environment example with placeholder values and ignore your local environment file. Verify the tracked file list and explain why example values should never be live credentials.",
        ),
      ),
      section(
        "Team workflow",
        lesson(
          "Branches and Focused Features",
          "A branch is a movable reference to a commit. A feature branch lets work progress without changing the shared branch immediately. Keep a feature small enough to review and bring in shared changes deliberately. Check the working tree before switching contexts so unfinished edits are not confused with another feature.",
          "git switch -c feature/course-search\n# implement and commit\ngit log --oneline --all --graph",
          "Create a branch for search and another for a UI fix. Compare their histories. Explain which changes a reviewer would see in each branch.",
        ),
        lesson(
          "Merges and Conflict Resolution",
          "A conflict occurs when Git cannot combine competing changes automatically. Read both versions, understand the intended final behavior and edit a coherent result. Conflict markers are a prompt for human judgment, not a reason to choose one side blindly. Test after resolving a conflict.",
          "<<<<<<< feature\nSearch by title\n=======\nSearch by category\n>>>>>>> main\nFinal behavior can support both filters.",
          "Simulate two branches modifying the same function. Resolve the conflict to preserve both intended behaviors and run a small verification. Document the decision in the merge commit.",
        ),
      ),
      section(
        "Review & delivery",
        lesson(
          "Pull Requests and Review",
          "A pull request makes a proposed change concrete for review. Explain the problem, resulting behavior and verification. Reviewers should check correctness, readability and user impact. Respond to feedback by discussing the tradeoff and updating the code where needed.",
          'PR description: "Adds category filtering to the catalogue. Empty results show a clear state. Verified with browser search and a production build."',
          "Write a pull request description for a course feature. Review a partner’s change and leave two actionable comments linked to specific behavior rather than personal preference.",
        ),
        lesson(
          "Collaboration Capstone",
          "A strong repository makes onboarding and assessment easier. Include setup instructions, environment examples, a clear project structure and reproducible checks. Commit at meaningful checkpoints and avoid a single huge final snapshot. Use an issue checklist to divide a project into reviewable tasks.",
          "Checklist: install, configure, migrate, seed, run, test.\nEach task: owner, acceptance criteria, relevant checks.",
          "Complete a two-person feature workflow with branches, a review and a resolved conflict. Submit the repository and a short reflection on how version control protected your work.",
          40,
        ),
      ),
    ],
  ),
  course(
    "data",
    "Data Analysis with Python",
    "Data Science",
    "Intermediate",
    "Clean messy datasets and communicate useful findings with confidence.",
    "Work through an enrolment dataset using Python, pandas and charts. Learn to inspect data quality, transform columns, group results and avoid misleading visualisations. Finish with a reproducible analysis notebook and a short evidence-based report.",
    [
      "Inspect and clean tabular datasets",
      "Transform and aggregate data with pandas",
      "Choose clear charts for different questions",
      "Produce a reproducible notebook and report",
    ],
    ["Python fundamentals", "Jupyter Notebook and pandas installed"],
    "r-uOLxNrNk8",
    [
      section(
        "Data foundations",
        lesson(
          "Questions, Datasets and Notebooks",
          "Start an analysis with a concrete question and a description of the data source. A notebook combines executable code and explanation, but hidden execution order can make results irreproducible. Inspect the schema, units and missing values before drawing conclusions. Keep a copy of raw input separate from cleaned output.",
          "Question: Which categories have the highest enrolment growth?\nColumns: course_id, category, enrolled_at, learner_id.\nCheck: duplicate rows, missing dates, timezone consistency.",
          "Create a small fictional enrolment CSV and a notebook describing its columns. Restart the kernel and run all cells. Verify that results do not depend on a forgotten earlier action.",
        ),
        lesson(
          "DataFrames and Column Types",
          "A DataFrame is a labelled table. Column types affect filtering, arithmetic and aggregation. Parse dates deliberately and inspect dtypes rather than assuming imported values are correct. Use explicit column selections when preparing a report so unnecessary personal information is not included.",
          'import pandas as pd\ndf = pd.read_csv("enrolments.csv")\ndf["enrolled_at"] = pd.to_datetime(df["enrolled_at"])\nprint(df.dtypes)',
          "Load your CSV, parse dates and create a report-safe subset of columns. Add an invalid date and document the policy you choose for that row.",
        ),
      ),
      section(
        "Cleaning & exploration",
        lesson(
          "Missing Values and Duplicates",
          "Missing data can mean unknown, not applicable or not collected. Replacing every missing value with zero can distort meaning. Define a deduplication key that matches the real-world record identity. Report how many rows are removed or changed so the cleaning process is auditable.",
          'duplicate_count = df.duplicated(["learner_id","course_id"]).sum()\nclean = df.drop_duplicates(["learner_id","course_id"])',
          "Introduce duplicate enrolments and missing categories. Clean the dataset, record the decisions and compare summary counts before and after. Explain which assumptions could affect the conclusions.",
        ),
        lesson(
          "Grouping and Derived Metrics",
          "Grouping answers questions at a defined level, such as enrolments per category. Decide whether a metric counts enrolments, unique learners or courses because these differ. Derive percentages from consistent numerators and denominators. Check small groups before ranking them against large groups.",
          'summary = clean.groupby("category").agg(\n    enrolments=("course_id","size"),\n    learners=("learner_id","nunique")\n)',
          "Create category and weekly enrolment summaries. Compare enrolment counts with unique learner counts. Explain why the most enrolled category is not automatically the most effective teaching category.",
        ),
      ),
      section(
        "Communicating findings",
        lesson(
          "Charts and Honest Comparisons",
          "Choose a bar chart for category comparisons and a line chart for a time series. Label axes and units, keep scales understandable and avoid visual decoration that hides differences. A chart shows an association; it does not prove that one event caused another. Include the sample period and limitations.",
          'summary["enrolments"].sort_values().plot.barh()\n# Add a descriptive title and axis labels before exporting.',
          "Produce two charts and a short explanation for each. Show one misleading chart choice, correct it and explain how the original could mislead a reader.",
        ),
        lesson(
          "Analysis Portfolio Capstone",
          "A reproducible report includes the question, source, cleaning decisions, analysis and limitations. Separate observations from interpretations. Keep notebook outputs concise and provide instructions to rerun the work. An executive summary should answer the original question using evidence from the analysis.",
          "Report structure: question → data quality → method → findings → limitations → next steps.",
          "Deliver your notebook and a one-page report on course enrolments. Have a peer rerun the notebook from the raw CSV and verify two headline numbers.",
          40,
        ),
      ),
    ],
  ),
  course(
    "algorithms",
    "Data Structures & Problem Solving",
    "Computer Science",
    "Intermediate",
    "Choose the right structure and explain the cost of your solution.",
    "Study searching, sorting and core data structures through practical Python exercises. Compare time and space tradeoffs rather than memorising implementations. The final project models a prerequisite graph and explains the complexity of its operations.",
    [
      "Compare algorithm time and space costs",
      "Use stacks, queues and hash-based lookups",
      "Implement searching and sorting strategies",
      "Model dependencies with graphs",
    ],
    ["Python lists, dictionaries and functions", "Basic algebra"],
    "pkYVOmU3MgA",
    [
      section(
        "Thinking about complexity",
        lesson(
          "Big O and Growth Rates",
          "Complexity describes how resource use grows with input size. O(1), O(log n), O(n) and O(n squared) have very different scaling behavior. Big O ignores constant factors, so it is a reasoning tool rather than an exact stopwatch. Consider memory as well as runtime.",
          "Scanning n courses once is O(n).\nComparing every course with every other course is O(n²).\nA hash lookup is typically O(1) on average.",
          "Compare a single scan with a nested loop on lists of increasing size. Record timing but also count operations. Explain a case where constants matter for a small dataset.",
        ),
        lesson(
          "Linear and Binary Search",
          "Linear search checks items sequentially and works on unsorted data. Binary search repeatedly halves a sorted search range. The sorted precondition is essential: applying binary search to unsorted input gives unreliable answers. Use clear boundary conventions to avoid off-by-one errors.",
          "low, high = 0, len(values)-1\nwhile low <= high:\n    mid = (low+high)//2\n    # compare values[mid] and move one boundary",
          "Implement both searches. Test an empty list, one item, a missing item and duplicates. Explain whether sorting first is worthwhile for one search versus many searches.",
        ),
      ),
      section(
        "Useful structures",
        lesson(
          "Stacks and Queues",
          "A stack uses last-in-first-out order and supports operations such as undo or matching brackets. A queue uses first-in-first-out order and is useful for scheduling or breadth-first traversal. Choose a container with efficient operations at the required ends. The structure should reflect the problem behavior.",
          'from collections import deque\nqueue = deque(["task A","task B"])\nnext_task = queue.popleft()\nqueue.append("task C")',
          "Implement a study-session queue and an undo stack for task edits. Demonstrate how the same three items are processed in different orders by each structure.",
        ),
        lesson(
          "Hash Tables and Sets",
          "Hash-based containers support fast membership and key lookup on average. Keys must have stable equality and hash behavior. Sets represent unique items and are useful for duplicate detection. A list may still be appropriate when order or repeated values are central to the problem.",
          'seen = set()\nfor course_id in enrolment_ids:\n    if course_id in seen:\n        print("Duplicate enrolment")\n    seen.add(course_id)',
          "Detect duplicate course enrolments using a set and compare it with nested loops. Explain how you would preserve the order of first occurrence while removing duplicates.",
        ),
      ),
      section(
        "Algorithms in practice",
        lesson(
          "Sorting and Stable Order",
          "Sorting arranges records by a comparison key. A stable sort preserves the order of equal-key items, which matters when applying multiple ordering rules. Understand a simple sort such as insertion sort before comparing it with more efficient approaches. Be explicit about whether sorting mutates input.",
          'courses_sorted = sorted(courses, key=lambda c: (c["category"], c["title"]))',
          "Implement insertion sort on lesson positions and compare it with Python’s built-in sorted. Include equal positions and explain the tie-breaking rule your application needs.",
        ),
        lesson(
          "Graphs and Prerequisite Planner",
          "A graph models vertices and edges. A course prerequisite graph uses directed edges to indicate dependency. Breadth-first and depth-first traversal explore different orders. Cycles may make a prerequisite schedule impossible, so detect them instead of silently returning an incomplete plan.",
          "Graph: HTML → CSS → JavaScript → React.\nAlso: Python → Data Analysis.\nA valid study order places every prerequisite before its dependent course.",
          "Build a prerequisite planner and display one valid study order. Test a disconnected course and a cycle. Explain the complexity using the number of vertices and edges.",
          40,
        ),
      ),
    ],
  ),
  course(
    "ux",
    "UI/UX Design: Research to Prototype",
    "Design",
    "Beginner",
    "Design useful interfaces with research, wireframes and interactive prototypes.",
    "Work through a redesign of a course enrolment experience. Define user needs, map the journey, create accessible screens and test a prototype. Focus on evidence and interaction clarity rather than decorative mockups.",
    [
      "Turn user observations into design requirements",
      "Map a clear enrolment journey",
      "Build wireframes and reusable components",
      "Run a small usability test and revise a prototype",
    ],
    [
      "A free Figma account or another design tool",
      "No previous design experience",
    ],
    "c9Wg6Cb_YlU",
    [
      section(
        "Understanding the user",
        lesson(
          "Research Questions and Interviews",
          "A design problem should identify the user, context and difficulty. Ask about recent behavior instead of asking users to predict what they would like. Avoid leading questions and collect only information relevant to the study. A small student exercise can reveal issues but should not claim to represent all users.",
          'Leading: "Do you like our easy enrolment button?"\nBetter: "Tell me about the last time you signed up for an online course."',
          "Interview two volunteers about choosing a course. Record recurring problems, distinguish observations from assumptions and write three research-backed design requirements.",
        ),
        lesson(
          "User Journeys and Information Architecture",
          "A journey maps the steps toward a goal and the questions or obstacles at each step. Information architecture groups content so users can find it. Course discovery, evaluating a curriculum and starting a lesson are distinct tasks. Make the next action clear without hiding important information.",
          "Discover → compare → read curriculum → enrol → start lesson → resume.\nQuestions: Is this my level? What will I learn? Where did I stop?",
          "Map an LMS enrolment journey. Identify two points where information is missing and sketch how the interface could answer those questions.",
        ),
      ),
      section(
        "Designing the interface",
        lesson(
          "Wireframes and Visual Hierarchy",
          "Wireframes explore structure before visual polish. Use size, spacing and grouping to guide attention to the main action. A busy dashboard should still have a clear starting point. Keep labels specific and avoid filling space with invented statistics. Layout should respond to actual content length.",
          "Dashboard priority: resume lesson → progress summary → activity → recommended next course.\nSecondary actions belong below or beside the primary learning task.",
          "Sketch desktop and mobile dashboards using the same real data. Explain how a learner with no enrolments sees a useful empty state instead of a blank page.",
        ),
        lesson(
          "Components, States and Accessibility",
          "A reusable component needs states such as default, hover, focus, disabled, loading and error. Design readable contrast, clear focus outlines and labels that do not rely only on color. Components should accommodate longer text and larger font sizes. Consistency helps users predict how interactions work.",
          "Course card states: published, enrolled, unavailable.\nForm states: empty, valid, submitting, error, saved.",
          "Create a small component set for course cards and forms. Show loading and error variants. Test readability with grayscale, keyboard focus and a long course title.",
        ),
      ),
      section(
        "Testing & iteration",
        lesson(
          "Prototyping and Usability Tasks",
          "An interactive prototype tests the sequence of actions before building the full system. Give participants a goal rather than a list of buttons to click. Observe hesitation and mistakes, ask neutral follow-up questions and avoid coaching. Record issues by impact and frequency.",
          'Task: "Find a beginner course about databases and start the first lesson."\nObserve: filter discovery, curriculum comprehension and enrolment feedback.',
          "Run a short prototype test with two participants. Record completion, observed problems and quotes with consent. Prioritise fixes without claiming statistical significance.",
        ),
        lesson(
          "LMS Redesign Capstone",
          "An effective design case study explains the problem, evidence, alternatives and final decisions. Connect changes to observed user needs. Show a before/after flow and document unresolved questions. Include content and failure states so the design can be implemented without guesswork.",
          "Deliverables: journey, wireframes, component states, clickable prototype, test findings and revised screens.",
          "Present your enrolment redesign as a short case study. Explain three changes driven by research or testing and one tradeoff you would revisit with more evidence.",
          40,
        ),
      ),
    ],
  ),
  course(
    "linux",
    "Linux & Command-Line Essentials",
    "Developer Tools",
    "Beginner",
    "Navigate files, automate routine tasks and understand your development environment.",
    "Practice Linux commands in an isolated development environment. Learn paths, permissions, processes and shell pipelines, then write a small reporting script. Exercises use a disposable project folder so system files remain untouched.",
    [
      "Navigate and inspect files confidently",
      "Explain ownership and basic permissions",
      "Compose filters and shell pipelines",
      "Write a repeatable reporting script",
    ],
    [
      "Linux, WSL or a disposable Linux container",
      "Use a dedicated practice folder",
    ],
    "sWbUDq4S6Y8",
    [
      section(
        "Working with files",
        lesson(
          "Paths and Directory Navigation",
          "The filesystem is a tree rooted at /. Absolute paths begin at the root; relative paths begin at the current working directory. Inspect where you are before modifying files. Quoting a path keeps spaces from becoming separate arguments. Use an isolated practice folder to avoid accidental edits to important files.",
          "pwd\nmkdir -p ~/studyflow-lab\ncd ~/studyflow-lab\nls -la",
          "Create a lab folder with notes and scripts subdirectories. Navigate using absolute and relative paths. Explain the meaning of . and .. and test a file name containing a space.",
        ),
        lesson(
          "Reading and Searching Text",
          "Text tools help inspect configuration and logs without opening every file manually. Use head and tail for excerpts, less for paging and grep or rg for matching lines. Understand whether a command treats a pattern literally or as a regular expression. Avoid printing secrets while investigating files.",
          'head -n 10 notes.txt\ntail -n 20 app.log\nrg -n "ERROR" app.log',
          "Create a fictional application log and find errors by date and message. Compare literal and pattern matching. Produce an excerpt that contains useful context without unrelated sensitive fields.",
        ),
      ),
      section(
        "The operating environment",
        lesson(
          "Permissions and Ownership",
          "Permissions control what an owner, group and others can read, write or execute. Executing a script differs from reading it. Grant only the access needed for a task rather than making all files writable by everyone. Inspect permissions before changing them and restrict experiments to your lab folder.",
          "ls -l report.sh\nchmod u+x report.sh\n./report.sh",
          "Create a script in your lab folder, observe an execution failure and enable execution for its owner. Explain why making the file world-writable is unnecessary.",
        ),
        lesson(
          "Processes and Environment Variables",
          "A process is a running program with an ID and environment. Tools such as ps show active processes. Environment variables configure a process without changing source code. Keep configuration examples separate from real secrets and avoid reusing important system variable names.",
          'ps -ef\nexport STUDYFLOW_PORT=5000\nprintf "%s\\n" "$STUDYFLOW_PORT"',
          "Run a simple foreground command and inspect it from another terminal. Configure a lab script with a task-specific variable. Explain why a variable set in one terminal may not appear in another.",
        ),
      ),
      section(
        "Automation",
        lesson(
          "Pipelines and Exit Status",
          "A pipeline sends one command’s output to the next command’s input. Filters work best when each step has a clear purpose. Exit status communicates success or failure, but a pipeline can hide an earlier failure unless the shell is configured appropriately. Quote variables and validate input paths.",
          'rg "ERROR" app.log | sort | uniq -c\n# Inspect each stage separately before composing the pipeline.',
          "Build a report that counts repeated log messages. Compare the raw lines with the summary and test an empty log. Explain how you would detect an unreadable input file.",
        ),
        lesson(
          "Developer Report Script Capstone",
          "A small automation script should be repeatable and explicit about its inputs and outputs. Validate the lab directory, handle missing files and avoid destructive cleanup. Include a help message and document the environment it expects. Review a script as code before running it.",
          "Report: file count, log error count, current date and supplied project name.\nInputs: one validated lab directory; no system file modification.",
          "Write a report script for your practice folder. Test paths with spaces, missing files and repeated runs. Include a README and explain every command used.",
          40,
        ),
      ),
    ],
  ),
  course(
    "cs",
    "Computer Science Foundations",
    "Computer Science",
    "Beginner",
    "Understand how computers represent information and solve problems.",
    "Explore computational thinking, binary representation, memory and abstraction. Relate each idea to a small program or diagram and finish with a solution design for a campus problem. The companion university lecture series extends the topics beyond this guided introduction.",
    [
      "Decompose problems into testable steps",
      "Explain binary representation and memory",
      "Compare abstraction levels in software",
      "Design and communicate a small solution",
    ],
    ["Curiosity and basic arithmetic", "Optional Python familiarity"],
    "8mAITcNt710",
    [
      section(
        "Computational thinking",
        lesson(
          "Decomposition and Pseudocode",
          "Decomposition breaks a problem into smaller operations with clear inputs and outputs. Pseudocode describes the algorithm without depending on one language. Think about unusual inputs before implementation. A correct solution should be understandable enough for another person to follow step by step.",
          "Problem: assign study rooms.\nInput: requests with date, capacity and duration.\nSteps: validate request → find available room → reserve → confirm.",
          "Write pseudocode for reserving a study room. Include invalid requests and no available room. Have a partner execute the steps manually using a small example.",
        ),
        lesson(
          "Binary and Information Representation",
          "A bit has two possible values. Groups of bits represent numbers, text and other information through agreed encodings. Binary place values are powers of two. The same bits can have different meanings depending on their interpretation; a computer does not infer the intended meaning by itself.",
          "Binary 1011 = 8 + 0 + 2 + 1 = 11.\nWith 4 unsigned bits, the values range from 0 through 15.",
          "Convert five small decimal numbers to binary. Explain the largest value an unsigned byte can hold and why text encoding must be agreed between systems.",
        ),
      ),
      section(
        "Programs & memory",
        lesson(
          "Algorithms and Correctness",
          "An algorithm is a finite sequence of steps for a task. Correctness means producing the expected result for valid inputs, including edge cases. A loop invariant describes something that remains true as a loop progresses. Use examples and reasoning together instead of relying on one successful run.",
          "Find maximum: keep the greatest value seen so far while scanning the list.\nInvariant: after each iteration, maximum is greatest among processed values.",
          "Describe and implement a maximum-finding algorithm. Handle an empty list explicitly. Explain the invariant and show how it supports the correctness argument.",
        ),
        lesson(
          "Memory, Values and References",
          "Programs store values in memory and may refer to the same object from multiple places. Updating a shared object can affect several parts of a program. Distinguish copying a reference from copying data. Higher-level languages manage many memory details, but understanding identity still prevents bugs.",
          'a = {"completed": False}\nb = a\nb["completed"] = True\n# a now refers to the changed object too.',
          "Draw a memory/reference diagram for two variables pointing to one task object. Compare it with two independent objects and explain the effects of each update.",
        ),
      ),
      section(
        "From ideas to systems",
        lesson(
          "Abstraction and System Boundaries",
          "An abstraction exposes the operations a user needs while hiding details they do not need to manipulate. A frontend, API and database each have distinct responsibilities. Clear boundaries make a system easier to explain and test. An abstraction should reduce confusion, not introduce machinery without a practical purpose.",
          "Frontend: display enrol button and feedback.\nAPI: validate session and prevent duplicate enrolment.\nDatabase: store relationships and enforce uniqueness.",
          "Explain the LMS enrolment flow using a three-part diagram. Assign validation, display state and durable storage to the appropriate part. Identify a failure possible at each boundary.",
        ),
        lesson(
          "Campus Solution Design Capstone",
          "A solution design connects a problem to requirements, data and algorithms. Define a small scope that can be completed and tested. State assumptions and constraints, use examples to verify behavior and communicate limitations. A working simple solution is stronger than a broad design with unfinished core paths.",
          "Example: study-room booking with users, rooms and reservations.\nCore checks: capacity, time overlap, user identity and cancellation.",
          "Design a small campus application with a data model, one complete user journey and five test cases. Present one design tradeoff and explain why it fits a university project.",
          40,
        ),
      ),
    ],
  ),
];
